### ISSUE TITLE
Map showing user's location + message about police being dispatched

### ISSUE THREAD

**Issue by tdingman** [maxnuss/am-i-on-acid#1]
The app should request location info, show the user's location on a map, and tell the user the police are being dispatched to their location

**Comment by tdingman** [comment]
@maxnuss need that police car icon we discussed. As a reminder:

* Bird's eye view
* Flashing lights
* 32x32 or greater, with transparent background

**Comment by maxnuss** [comment]
![cops](https://user-images.githubusercontent.com/2905696/60199662-6a31e980-9812-11e9-9eeb-8e51d6c4516c.gif)

**Comment by maxnuss** [comment]
![busted](https://user-images.githubusercontent.com/2905696/60199762-a49b8680-9812-11e9-8e86-2613caf9d8a8.gif)
