### ISSUE TITLE
Location tracking doesn't work without HTTPS

### ISSUE THREAD

**Issue by tdingman** [maxnuss/am-i-on-acid#5]
The latest deployment has the following error in the JS:

> getCurrentPosition() and watchPosition() no longer work on insecure origins. To use this feature, you should consider switching your application to a secure origin, such as HTTPS. See https://goo.gl/rStTGz for more details.

@maxnuss I think this means you have to switch your site to HTTPS?

**Comment by tdingman** [comment]
jk jk, I think Sean will have to change the settings. Not sure if it's on the server or on the domain registration

**Comment by spennino** [comment]
Yeah this is an issue with google domains and heroku. Putting this link here so I don't forget about it https://medium.com/employbl/https-ssl-on-heroku-with-google-domains-as-dns-provider-c55c438556c6

**Comment by tdingman** [comment]
I will take this issue while Sean continues being a deadbeat. I bet I can add a conditional that removes the blocker if the site is http only

**Comment by tdingman** [comment]
K, the commit I just made fixes the issue I think. I'm not sure how to test http locally, soooo

**Comment by maxnuss** [comment]
@tdingman commit didn't fix it. This is definitely on @spennino to fix, I just enabled https for all my other hosted sites but can't do it here.

**Comment by spennino** [comment]
Ok this is working, but with one tradeoff. The easiest solution was to have am-i-on-acid.com forward to https://am-i-on-acid.herokuapp.com/. In order to preserve the domain, and have ssl enabled, we'd have to bump to a paid tier of Heroku ($7/mo). I imagine there's a free solution or super cheap solution to this problem we can migrate to later though

**Comment by spennino** [comment]
also true for amionacid.com, both domains are fowarding

**Comment by maxnuss** [comment]
@spennino is there a reason we can't just host this on github pages?
