### ISSUE TITLE
Map not loading

### ISSUE THREAD

**Issue by tdingman** [maxnuss/am-i-on-acid#8]
<img width="1317" alt="Screen Shot 2019-07-25 at 4 02 52 PM" src="https://user-images.githubusercontent.com/3240630/61904860-b8133d80-aef5-11e9-8d23-a9ce3a157181.png">

The error in the console is about the URL not being authorized, but here are my API key auth settings:

<img width="574" alt="Screen Shot 2019-07-25 at 4 03 57 PM" src="https://user-images.githubusercontent.com/3240630/61904909-d842fc80-aef5-11e9-9a6a-f27a128f961c.png">

I copy and pasted the URL from the error - the URL the error says I need to authorize! - and added it to the list of authorized URLS. No dice.

**Comment by tdingman** [comment]
Saving settings is kinda busted, may actually be a bug with Google Cloud. Specifically:

1. Edit restricted URLs
2. Save

Expected: page refreshes and shows new settings

Actual: Save button turns grey and says "SAVING" with a spinner next to it perpetually

Google Cloud throws a bunch of errors in the console too.

**Comment by tdingman** [comment]
I filed an issue with Google: https://issuetracker.google.com/issues/138314235

**Comment by spennino** [comment]
@tdingman if you add https://am-i-on-acid.herokuapp.com/ to allowed referrers I think it should work

**Comment by tdingman** [comment]
Main site and deployment on maxnuss.com work! I think it's a coincidence though, since now there are no errors in the Google Cloud website console, but I'll take it
