### ISSUE TITLE
Does not resize on mobile on Chrome for Android

### ISSUE THREAD

**Issue by tdingman** [maxnuss/am-i-on-acid#9]
Death to horizontal scrolling

**Comment by tdingman** [comment]
Should also shrink BUSTED so the map is above the fold

**Comment by tdingman** [comment]
@maxnuss if you have CSS knowledge that can quickly fix, please advise/reassign

**Comment by maxnuss** [comment]
@tdingman it used to, something about the location integration must have broken it. I'll investigate
